//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace AngularWebApp.DB
{
	/// <summary>
	/// Database       : aspnet-AngularWebApp
	/// Data Source    : (localdb)\mssqllocaldb
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class LinqDB : LinqToDB.Data.DataConnection
	{
		public LinqDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public LinqDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}
}

#pragma warning restore 1591
